engines:
  eslint:
    enabled: false
  duplication:
    enabled: false
ratings:
   paths:
   - "packages/*/src/**/*.js"
exclude_paths:
- "gulpfile.js"
- "README.md"
- "examples/**"
- "package.json"
- "packages/*/test/**/*"
- "packages/*/dist/**/*"
