export default {
  REQUEST_IDLE: 'REQUEST_IDLE',
  REQUEST_PENDING: 'REQUEST_PENDING',
  REQUEST_FAILED: 'REQUEST_FAILED',
  REQUEST_SUCCEEDED: 'REQUEST_SUCCEEDED',
  UPDATE_RESOURCES: 'UPDATE_RESOURCES',
};
